blank_issues_enabled: false
contact_links:
  - name: Kometa Wiki
    url: https://kometa.wiki/en/latest/home/scripts/imagemaid.html
    about: Please check the wiki to see if your question has already been answered.
  - name: Discord
    url: https://kometa.wiki/en/latest/discord/
    about: Please use the Kometa Discord to ask for support.